/**
 * Upcoming shows.
 *
 * AUTO-GENERATED by the scheduled Claude sync task (via scripts/sync-shows.mjs)
 * from the Google Calendar iCal feed, with a web-research pass. Manual edits
 * are overwritten on the next sync — change the calendar event instead, or
 * adjust the task prompt (see scripts/SHOWS_SYNC_SETUP.md).
 * `date` is ISO (YYYY-MM-DD). Past shows are filtered out on the page. Set
 * `ticketUrl` to null for free / at-the-door shows; the card shows "Free".
 */

export type Show = {
  id: string;
  date: string; // ISO date, e.g. "2026-07-31"
  venue: string;
  city: string;
  /** Optional note, e.g. "with The Doomed" or "Festival" */
  note?: string;
  ticketUrl: string | null;
};

export const shows: Show[] = [
  {
    id: "sly-grog-lounge-2026-07-31",
    date: "2026-07-31",
    venue: "Sly Grog Lounge",
    city: "Asheville, NC",
    note: "with Broadslab",
    ticketUrl: "https://theslygrogavl.com/",
  },
  {
    id: "avl-sounds-fest-2026-08-08",
    date: "2026-08-08",
    venue: "AVL Sounds Fest",
    city: "Asheville, NC",
    note: "Aug 6-9 / multi-venue festival",
    ticketUrl: "https://www.etix.com/ticket/p/36960932/avl-sounds-fest-asheville-avl-sounds-fest",
  },
];
