/**
 * Upcoming shows.
 *
 * AUTO-GENERATED by scripts/sync-shows.mjs from the Google Calendar iCal feed.
 * Manual edits will be overwritten on the next sync. To change a show, edit the
 * calendar event instead. `date` is ISO (YYYY-MM-DD). Past shows are filtered
 * out automatically on the page. Set `ticketUrl` to null for free / at-the-door
 * shows and the card shows "Free" instead of a button.
 */

export type Show = {
  id: string;
  date: string; // ISO date, e.g. "2026-07-31"
  venue: string;
  city: string;
  /** Optional note, e.g. "with The Doomed" or "Festival" */
  note?: string;
  ticketUrl: string | null;
};

export const shows: Show[] = [
  {
    id: "broadslab-2026-07-31",
    date: "2026-07-31",
    venue: "Broadslab",
    city: "Benson, NC",
    note: "SLYGROG",
    ticketUrl: null,
  },
  {
    id: "avl-sounds-fest-2026-08-08",
    date: "2026-08-08",
    venue: "AVL Sounds Fest",
    city: "Asheville, NC",
    note: "AVL Sounds Fest",
    ticketUrl: null,
  },
];
